In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
pwd

'C:\\Users\\Shrijan Aryal\\Titanic'

In [69]:
ls

 Volume in drive C is Windows
 Volume Serial Number is E8A9-D000

 Directory of C:\Users\Shrijan Aryal\Titanic

04/03/2025  09:05 PM    <DIR>          .
04/03/2025  09:05 PM    <DIR>          ..
03/30/2025  12:04 AM    <DIR>          .ipynb_checkpoints
03/29/2025  04:51 PM            33,673 best_model.pkl
04/03/2025  08:14 PM            42,939 best_model2.pkl
04/03/2025  09:05 PM            42,663 best_model3.pkl
04/03/2025  08:51 PM             3,258 submissionApril.csv
04/03/2025  08:52 PM             1,008 submissionApril.zip
03/30/2025  09:40 PM             3,258 submissionI.csv
03/30/2025  09:41 PM             1,000 submissionI.zip
03/24/2025  02:23 PM            28,629 test.csv
04/03/2025  09:04 PM           828,984 Titanic.ipynb
04/03/2025  09:04 PM           113,106 Titanic_prediction.ipynb
03/30/2025  12:03 AM            31,102 titanic_predictions.csv
04/03/2025  08:50 PM            31,948 titanic_predictions2.csv
03/26/2025  06:49 PM            61,194 Titanic_train.csv
              13 File(s)      1,222,762 bytes
               3 Dir(s)  308,723,929,088 bytes free

In [70]:
data = pd.read_csv('test.csv')

In [71]:
data.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [72]:
for item in data.columns:
    print(f'Total missing vlaues for {item}: {data[item].isnull().sum()}')

Total missing vlaues for PassengerId: 0
Total missing vlaues for Pclass: 0
Total missing vlaues for Name: 0
Total missing vlaues for Sex: 0
Total missing vlaues for Age: 86
Total missing vlaues for SibSp: 0
Total missing vlaues for Parch: 0
Total missing vlaues for Ticket: 0
Total missing vlaues for Fare: 1
Total missing vlaues for Cabin: 327
Total missing vlaues for Embarked: 0

In [73]:
print(f'The mean of age is {data['Age'].mean()}, the median is {data['Age'].median()}, and the standard deviation is {data['Age'].std()} ')

The mean of age is 30.272590361445783, the median is 27.0, and the standard deviation is 14.181209235624422

In [74]:
# We know, skewness = 3(mean-median)/ standard deviation
skewness = (3*(data['Age'].mean()-data['Age'].median()))/(data['Age'].std())
print(f'The skewness of the data for the age is: {skewness}')

The skewness of the data for the age is: 0.6923084570019783

In [75]:
data['Fare'].fillna(data['Fare'].median(), inplace=True)
print(f'The total missing values for the Fare is {data['Fare'].isnull().sum()}')

The total missing values for the Fare is 0

In [76]:
data['Family'] = 1 + data['SibSp'] + data['Parch']

In [77]:
import pandas as pd

data['Title'] = data['Name'].str.extract(r' ([A-Za-z]+)\.')

# Check unique titles
print(data['Title'].value_counts())

Title
Mr        240
Miss       78
Mrs        72
Master     21
Col         2
Rev         2
Ms          1
Dr          1
Dona        1
Name: count, dtype: int64

In [78]:
# Define title mapping
title_mapping = {
    "Mr": "Mr", 
    "Miss": "Miss", 
    "Mrs": "Mrs", 
    "Master": "Master",
    "Dr": "Rare", "Rev": "Rare", "Mlle": "Miss", "Major": "Rare",
    "Col": "Rare", "Countess": "Rare", "Capt": "Rare", 
    "Ms": "Miss", "Sir": "Rare", "Lady": "Rare", 
    "Mme": "Mrs", "Don": "Rare", "Jonkheer": "Rare"
}

# Apply mapping
data['Title'] = data['Title'].map(title_mapping)

# Check the updated title distribution
print(data['Title'].value_counts())

Title
Mr        240
Miss       79
Mrs        72
Master     21
Rare        5
Name: count, dtype: int64

In [79]:
import pandas as pd
data = pd.get_dummies(data, columns=['Title'], drop_first=True)

In [80]:
data.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Family', 'Title_Miss',
       'Title_Mr', 'Title_Mrs', 'Title_Rare'],
      dtype='object')

In [81]:
# Convert boolean values to 0 and 1
title_columns = ['Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Rare']
data[title_columns] = data[title_columns].astype(int)

# Check if conversion was successful
print(data[title_columns].dtypes)
print(data.head())

Title_Miss    int32
Title_Mr      int32
Title_Mrs     int32
Title_Rare    int32
dtype: object
   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Family  Title_Miss  \
0  34.5      0      0   330911   7.8292   NaN        Q       1           0
1  47.0      1      0   363272   7.0000   NaN        S       2           0
2  62.0      0      0   240276   9.6875   NaN        Q       1           0
3  27.0      0      0   315154   8.6625   NaN        S       1           0
4  22.0      1      1  3101298  12.2875   NaN        S       3           0

   Title_Mr  Title_Mrs  Title_Rare
0         1          0           0
1         0          1           0
2         1          0           0
3         1          0           0
4         0          1           0

In [82]:
data['IsElderly'] = (data['Age'] >= 60).astype(int)

In [83]:
data.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Family', 'Title_Miss',
       'Title_Mr', 'Title_Mrs', 'Title_Rare', 'IsElderly'],
      dtype='object')

In [84]:
# One-hot encode the 'Sex' column
data = pd.get_dummies(data, columns=['Sex'], drop_first=True)

print(data.columns)

Index(['PassengerId', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked', 'Family', 'Title_Miss', 'Title_Mr',
       'Title_Mrs', 'Title_Rare', 'IsElderly', 'Sex_male'],
      dtype='object')

In [85]:
data['Pclass_Sex'] = data['Pclass'] * data['Sex_male']

In [86]:
data.head()

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family,Title_Miss,Title_Mr,Title_Mrs,Title_Rare,IsElderly,Sex_male,Pclass_Sex
0,892,3,"Kelly, Mr. James",34.5,0,0,330911,7.8292,NaN,Q,1,0,1,0,0,0,True,3
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,NaN,S,2,0,0,1,0,0,False,0
2,894,2,"Myles, Mr. Thomas Francis",62.0,0,0,240276,9.6875,NaN,Q,1,0,1,0,0,1,True,2
3,895,3,"Wirz, Mr. Albert",27.0,0,0,315154,8.6625,NaN,S,1,0,1,0,0,0,True,3
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,12.2875,NaN,S,3,0,0,1,0,0,False,0

In [87]:
col = ['Pclass','Family','Sex_male','Title_Miss',
       'Title_Mr', 'Title_Mrs', 'Title_Rare', 'IsElderly','Fare','Pclass_Sex']
data_missing = data[data['Age'].isnull()][col]
data_complete = data[data['Age'].notnull()][col]

In [88]:
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold


# Separate data with known and unknown ages from the original dataset
X_known = data_complete.loc[data['Age'].notnull(), col]
y_known = data.loc[data['Age'].notnull(), 'Age']
X_unknown = data.loc[data['Age'].isnull(), col]

# Define the RandomForestRegressor with grid search
rf_model = RandomForestRegressor(random_state=42)

# Define parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 3, 5, 7],
    'min_samples_split': [2, 5, 10]
}

# Perform GridSearchCV with 5-fold cross-validation
grid_search = GridSearchCV(
    estimator=rf_model, 
    param_grid=param_grid, 
    cv=5,  # 5-fold cross-validation
    scoring='neg_mean_squared_error',  # negative MSE for regression
    n_jobs=-1  # Use all available cores
)

# Fit the grid search
grid_search.fit(X_known, y_known)

# Best model details
print("Best Parameters:", grid_search.best_params_)

# Calculate RMSE from the best negative MSE score
best_rmse = np.sqrt(-grid_search.best_score_)
print(f"Best RMSE: {best_rmse}")

# Get the best model
best_rf_model = grid_search.best_estimator_

# Perform 5-fold cross-validation
cv = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(
    best_rf_model, 
    X_known, 
    y_known, 
    cv=cv, 
    scoring='neg_mean_squared_error'
)

# Convert to RMSE
cv_rmse_scores = np.sqrt(-cv_scores)

# Print cross-validation results
print("\nCross-Validation Results:")
print("RMSE scores:", cv_rmse_scores)
print("Mean RMSE: {:.4f} (+/- {:.4f})".format(
    cv_rmse_scores.mean(), 
    cv_rmse_scores.std() * 2
))

# Predict missing ages
predicted_ages = best_rf_model.predict(X_unknown)

# Create a copy of the original dataframe
data_imputed = data.copy()

# Fill missing ages with predictions
data_imputed.loc[data_imputed['Age'].isnull(), 'Age'] = predicted_ages

# Validation
print("\nMissing Age Values:")
print("Before imputation:", data['Age'].isnull().sum())
print("After imputation:", data_imputed['Age'].isnull().sum())

data['Age'] = data_imputed['Age']

Best Parameters: {'max_depth': 5, 'min_samples_split': 5, 'n_estimators': 50}
Best RMSE: 9.486042714525226

Cross-Validation Results:
RMSE scores: [10.52450596  9.50141008 10.71532733  8.97974666  9.67937392]
Mean RMSE: 9.8801 (+/- 1.2984)

Missing Age Values:
Before imputation: 86
After imputation: 0

In [89]:
import pandas as pd
import numpy as np
import re

# Function to extract the deck letter
def extract_deck(cabin):
    if pd.isna(cabin):
        return np.nan
    # If there are multiple cabins listed (e.g., "C23 C25"), take the first one.
    cabin = cabin.split()[0]
    return cabin[0]

# Function to extract the cabin number
def extract_cabin_number(cabin):
    if pd.isna(cabin):
        return np.nan
    cabin = cabin.split()[0]
    match = re.search(r'(\d+)', cabin)
    if match:
        return int(match.group(1))
    return np.nan

# Apply the functions to create new features
data['Deck'] = data['Cabin'].apply(extract_deck)
data['Cabin_Number'] = data['Cabin'].apply(extract_cabin_number)

In [90]:
def cabin_position(num):
    if pd.isna(num):
        return np.nan
    # You can adjust the threshold if needed
    return 'bow' if num < 50 else 'back'

data['Cabin_Position'] = data['Cabin_Number'].apply(cabin_position)

In [91]:
col = ['Pclass','Family','Sex_male','IsElderly','Fare','Pclass_Sex','Age']
data_missing = data[data['Cabin'].isnull()][col]
data_complete = data[data['Cabin'].notnull()][col]

In [92]:
data['Deck'].unique()

array([nan, 'B', 'E', 'A', 'C', 'D', 'F', 'G'], dtype=object)

In [93]:
deck_counts = data['Deck'].value_counts(dropna=False)
print(deck_counts)

Deck
NaN    327
C       35
B       18
D       13
E        9
F        8
A        7
G        1
Name: count, dtype: int64

In [94]:
data['Deck'] = data['Deck'].replace({'F': 'Other', 'G': 'Other'})

# Mapping the remaining categories to numerical values
deck_mapping = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E':4, 'Other': 5}
data['Deck'] = data['Deck'].map(deck_mapping)

In [95]:
data['Deck'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Deck, dtype: float64

In [96]:
data.head(2)

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,...,Title_Miss,Title_Mr,Title_Mrs,Title_Rare,IsElderly,Sex_male,Pclass_Sex,Deck,Cabin_Number,Cabin_Position
0,892,3,"Kelly, Mr. James",34.5,0,0,330911,7.8292,NaN,Q,...,0,1,0,0,0,True,3,NaN,NaN,NaN
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,NaN,S,...,0,0,1,0,0,False,0,NaN,NaN,NaN

In [97]:
col = ['Pclass','Family','Sex_male', 'IsElderly','Fare','Pclass_Sex','Age']

In [98]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# Assume data_complete is already defined and contains the necessary columns
# col contains feature column names, and 'Deck' is the target variable.
X_complete = data_complete[col]  # Features
y_complete = data[data['Deck'].notnull()]['Deck']  # Target variable

# Define models and their hyperparameter grids
models = {
    'LogisticRegression': {
        'model': LogisticRegression(random_state=42, max_iter=1000),
        'params': {
            'C': [0.01, 0.1, 1.0, 10.0],
            'solver': ['liblinear', 'lbfgs']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(random_state=42),
        'params': {
            'max_depth': [None, 3, 5, 7, 10],
            'min_samples_split': [2, 5, 10],
            'criterion': ['gini', 'entropy']
        }
    },
    'RandomForest': {
        'model': RandomForestClassifier(random_state=42),
        'params': {
            'n_estimators': [50, 100, 200],
            'max_depth': [None, 3, 5, 7],
            'min_samples_split': [2, 5, 10]
        }
    },
    'GradientBoosting': {
        'model': GradientBoostingClassifier(random_state=42),
        'params': {
            'n_estimators': [50, 100, 200],
            'learning_rate': [0.01, 0.1, 0.2],
            'max_depth': [3, 5, 7]
        }
    },
    'KNN': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7, 9],
            'weights': ['uniform', 'distance'],
            'algorithm': ['auto', 'ball_tree', 'kd_tree']
        }
    },
    'SVM': {
        'model': SVC(random_state=42),
        'params': {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf'],
            'gamma': ['scale', 'auto']
        }
    }
}

# List to collect the results
results = []

# Iterate through each model and perform grid search with 5-fold CV
for name, config in models.items():
    print(f"Tuning {name}...")
    grid = GridSearchCV(config['model'],
                        config['params'],
                        cv=5,
                        scoring='accuracy',  # Using accuracy for classification
                        n_jobs=-1)
    grid.fit(X_complete, y_complete)
    
    # Get the best accuracy score
    best_accuracy = grid.best_score_
    
    results.append({
        'Model': name,
        'Best_Accuracy': best_accuracy,
        'Best_Params': grid.best_params_
    })

# Convert results to a DataFrame and print
results_df = pd.DataFrame(results)
print("\nHyperparameter Tuning Results:")
print(results_df)

Tuning LogisticRegression...
Tuning DecisionTree...
Tuning RandomForest...
Tuning GradientBoosting...
Tuning KNN...
Tuning SVM...

Hyperparameter Tuning Results:
                Model  Best_Accuracy  \
0  LogisticRegression       0.450877
1        DecisionTree       0.526901
2        RandomForest       0.483626
3    GradientBoosting       0.538012
4                 KNN       0.484211
5                 SVM       0.472515

                                         Best_Params
0                     {'C': 0.01, 'solver': 'lbfgs'}
1  {'criterion': 'entropy', 'max_depth': 7, 'min_...
2  {'max_depth': None, 'min_samples_split': 2, 'n...
3  {'learning_rate': 0.01, 'max_depth': 3, 'n_est...
4  {'algorithm': 'auto', 'n_neighbors': 3, 'weigh...
5        {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}

In [99]:
# Filter for GradientBoosting results
best_gradient_boosting = results_df[results_df['Model'] == 'GradientBoosting']

# Display the best parameters for GradientBoosting
print("\nBest Parameters for GradientBoosting:")
print(best_gradient_boosting)

Best Parameters for GradientBoosting:
              Model  Best_Accuracy  \
3  GradientBoosting       0.538012

                                         Best_Params
3  {'learning_rate': 0.01, 'max_depth': 3, 'n_est...

In [100]:
col = ['Pclass','Family','Sex_male','IsElderly','Fare','Pclass_Sex','Age']
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.model_selection import KFold
from sklearn.ensemble import GradientBoostingClassifier


# Separate data with known and unknown ages from the original dataset
X_known = data_complete.loc[data['Deck'].notnull(), col]
y_known = data.loc[data['Deck'].notnull(), 'Deck']
X_unknown = data.loc[data['Deck'].isnull(), col]

# Define the RandomForestRegressor with grid search
gb_model = GradientBoostingClassifier(random_state=42)



# Define parameter grid
param_grid = {
    'max_depth': [3],
    'learning_rate': [0.01],
    'n_estimators': [50, 100, 200]
}


# Perform GridSearchCV with 5-fold cross-validation
grid_search = GridSearchCV(
    estimator=gb_model, 
    param_grid=param_grid, 
    cv=5,  # 5-fold cross-validation
    scoring='accuracy',  # negative MSE for regression
    n_jobs=-1  # Use all available cores
)

# Fit the grid search
grid_search.fit(X_known, y_known)

# Best model details
print("Best Parameters:", grid_search.best_params_)
print("Best accuracy:", grid_search.best_score_)

# Best model
best_model = grid_search.best_estimator_


# Perform 5-fold cross-validation
cv = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(
    best_model, 
    X_known, 
    y_known, 
    cv=cv, 
    scoring='accuracy'
)

# Convert to RMSE
cv_rmse_scores = np.sqrt(-cv_scores)

# Print cross-validation results
print("\nCross-Validation Results:")
print("Accuracy scores:", cv_scores)
print("Mean Accuracy: {:.4f} (+/- {:.4f})".format(
    cv_scores.mean(), 
    cv_scores.std() * 2
))

# Predict missing cabins
predicted_cabins = best_model.predict(X_unknown)

# Create a copy of the original dataframe
data_imputed = data.copy()

# Fill missing ages with predictions
data_imputed.loc[data_imputed['Deck'].isnull(), 'Deck'] = predicted_cabins

# Validation
print("\nMissing Age Values:")
print("Before imputation:", data['Deck'].isnull().sum())
print("After imputation:", data_imputed['Deck'].isnull().sum())

data['Deck'] = data_imputed['Deck']

Best Parameters: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 50}
Best accuracy: 0.5380116959064327

Cross-Validation Results:
Accuracy scores: [0.52631579 0.5        0.61111111 0.55555556 0.5       ]
Mean Accuracy: 0.5386 (+/- 0.0833)

Missing Age Values:
Before imputation: 327
After imputation: 0

C:\Users\Shrijan Aryal\AppData\Local\Temp\ipykernel_12848\1353726095.py:56: RuntimeWarning: invalid value encountered in sqrt
  cv_rmse_scores = np.sqrt(-cv_scores)

In [101]:
# Now, we remove few columns from the data that is not necessary for the prediction
data.columns

Index(['PassengerId', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked', 'Family', 'Title_Miss', 'Title_Mr',
       'Title_Mrs', 'Title_Rare', 'IsElderly', 'Sex_male', 'Pclass_Sex',
       'Deck', 'Cabin_Number', 'Cabin_Position'],
      dtype='object')

In [102]:
data.head()

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,...,Title_Miss,Title_Mr,Title_Mrs,Title_Rare,IsElderly,Sex_male,Pclass_Sex,Deck,Cabin_Number,Cabin_Position
0,892,3,"Kelly, Mr. James",34.5,0,0,330911,7.8292,NaN,Q,...,0,1,0,0,0,True,3,5.0,NaN,NaN
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,NaN,S,...,0,0,1,0,0,False,0,5.0,NaN,NaN
2,894,2,"Myles, Mr. Thomas Francis",62.0,0,0,240276,9.6875,NaN,Q,...,0,1,0,0,1,True,2,5.0,NaN,NaN
3,895,3,"Wirz, Mr. Albert",27.0,0,0,315154,8.6625,NaN,S,...,0,1,0,0,0,True,3,5.0,NaN,NaN
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,12.2875,NaN,S,...,0,0,1,0,0,False,0,5.0,NaN,NaN

In [134]:
selected_columns =  ['Sex_male', 'Age', 'Family', 'Fare', 'Deck','Pclass_Sex','IsElderly']
data1 = data1[selected_columns]  # Select only the desired columns

In [135]:
data1.head()

   Sex_male   Age  Family     Fare  Deck  Pclass_Sex  IsElderly
0         1  34.5       1   7.8292   5.0           3          0
1         0  47.0       2   7.0000   5.0           0          0
2         1  62.0       1   9.6875   5.0           2          1
3         1  27.0       1   8.6625   5.0           3          0
4         0  22.0       3  12.2875   5.0           0          0

In [136]:
data1['Sex_male'] = data1['Sex_male'].astype(int)

In [137]:
data1.head()

   Sex_male   Age  Family     Fare  Deck  Pclass_Sex  IsElderly
0         1  34.5       1   7.8292   5.0           3          0
1         0  47.0       2   7.0000   5.0           0          0
2         1  62.0       1   9.6875   5.0           2          1
3         1  27.0       1   8.6625   5.0           3          0
4         0  22.0       3  12.2875   5.0           0          0

In [138]:
ls

 Volume in drive C is Windows
 Volume Serial Number is E8A9-D000

 Directory of C:\Users\Shrijan Aryal\Titanic

04/03/2025  09:26 PM    <DIR>          .
04/03/2025  09:26 PM    <DIR>          ..
03/30/2025  12:04 AM    <DIR>          .ipynb_checkpoints
03/29/2025  04:51 PM            33,673 best_model.pkl
04/03/2025  08:14 PM            42,939 best_model2.pkl
04/03/2025  09:05 PM            42,663 best_model3.pkl
04/03/2025  09:24 PM            35,855 best_model4.pkl
04/03/2025  08:51 PM             3,258 submissionApril.csv
04/03/2025  08:52 PM             1,008 submissionApril.zip
04/03/2025  09:18 PM             3,258 submissionApril2.csv
04/03/2025  09:19 PM             1,010 submissionApril2.zip
03/30/2025  09:40 PM             3,258 submissionI.csv
03/30/2025  09:41 PM             1,000 submissionI.zip
03/24/2025  02:23 PM            28,629 test.csv
04/03/2025  09:25 PM           829,187 Titanic.ipynb
04/03/2025  09:26 PM           112,900 Titanic_prediction.ipynb
03/30/2025  12:03 AM            31,102 titanic_predictions.csv
04/03/2025  08:50 PM            31,948 titanic_predictions2.csv
04/03/2025  09:18 PM            31,948 titanic_predictions3.csv
03/26/2025  06:49 PM            61,194 Titanic_train.csv
              17 File(s)      1,294,830 bytes
               3 Dir(s)  309,175,816,192 bytes free

In [139]:
import pickle
with open('best_model4.pkl','rb') as file:
    best_model = pickle.load(file)

In [140]:
predictions = best_model.predict(data1)

In [141]:
import numpy as np
data1.loc[:, 'Survived'] = np.nan

In [142]:
data1.head()

   Sex_male   Age  Family     Fare  Deck  Pclass_Sex  IsElderly  Survived
0         1  34.5       1   7.8292   5.0           3          0       NaN
1         0  47.0       2   7.0000   5.0           0          0       NaN
2         1  62.0       1   9.6875   5.0           2          1       NaN
3         1  27.0       1   8.6625   5.0           3          0       NaN
4         0  22.0       3  12.2875   5.0           0          0       NaN

In [143]:
data1.loc[data1['Survived'].isnull(), 'Survived'] = predictions

In [144]:
data1.head()

   Sex_male   Age  Family     Fare  Deck  Pclass_Sex  IsElderly  Survived
0         1  34.5       1   7.8292   5.0           3          0       0.0
1         0  47.0       2   7.0000   5.0           0          0       1.0
2         1  62.0       1   9.6875   5.0           2          1       0.0
3         1  27.0       1   8.6625   5.0           3          0       0.0
4         0  22.0       3  12.2875   5.0           0          0       1.0

In [145]:
data1['Survived'] = data1['Survived'].astype(int)

In [146]:
data1.head()

   Sex_male   Age  Family     Fare  Deck  Pclass_Sex  IsElderly  Survived
0         1  34.5       1   7.8292   5.0           3          0         0
1         0  47.0       2   7.0000   5.0           0          0         1
2         1  62.0       1   9.6875   5.0           2          1         0
3         1  27.0       1   8.6625   5.0           3          0         0
4         0  22.0       3  12.2875   5.0           0          0         1

In [147]:
data.head()

,PassengerId,Name,Pclass,Sex_male,Age,Family,Fare,Embarked,Deck,Pclass_Sex,IsElderly,Ticket,Survived
0,892,"Kelly, Mr. James",3,1,34.5,1,7.8292,2,5.0,3,0,330911,0
1,893,"Wilkes, Mrs. James (Ellen Needs)",3,0,47.0,2,7.0000,1,5.0,0,0,363272,1
2,894,"Myles, Mr. Thomas Francis",2,1,62.0,1,9.6875,2,5.0,2,1,240276,0
3,895,"Wirz, Mr. Albert",3,1,27.0,1,8.6625,1,5.0,3,0,315154,0
4,896,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",3,0,22.0,3,12.2875,1,5.0,0,0,3101298,1

In [148]:
data1['PassengerId'] = data['PassengerId']
data1['Name'] = data['Name']
data1['Ticket'] = data['Ticket']

In [149]:
data1.head()

,Sex_male,Age,Family,Fare,Deck,Pclass_Sex,IsElderly,Survived,PassengerId,Name,Ticket
0,1,34.5,1,7.8292,5.0,3,0,0,892,"Kelly, Mr. James",330911
1,0,47.0,2,7.0000,5.0,0,0,1,893,"Wilkes, Mrs. James (Ellen Needs)",363272
2,1,62.0,1,9.6875,5.0,2,1,0,894,"Myles, Mr. Thomas Francis",240276
3,1,27.0,1,8.6625,5.0,3,0,0,895,"Wirz, Mr. Albert",315154
4,0,22.0,3,12.2875,5.0,0,0,1,896,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",3101298

In [150]:
# Define the new column order
new_column_order = (
    ['PassengerId', 'Name'] + 
    [col for col in data1.columns if col not in ['PassengerId', 'Name', 'Survived']] + 
    ['Survived']
)

# Reorder the DataFrame
data1 = data1[new_column_order]

In [151]:
data1.head()

,PassengerId,Name,Sex_male,Age,Family,Fare,Deck,Pclass_Sex,IsElderly,Ticket,Survived
0,892,"Kelly, Mr. James",1,34.5,1,7.8292,5.0,3,0,330911,0
1,893,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,2,7.0000,5.0,0,0,363272,1
2,894,"Myles, Mr. Thomas Francis",1,62.0,1,9.6875,5.0,2,1,240276,0
3,895,"Wirz, Mr. Albert",1,27.0,1,8.6625,5.0,3,0,315154,0
4,896,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,3,12.2875,5.0,0,0,3101298,1

In [152]:
data1.to_csv('titanic_predictions4.csv', index=False)

In [132]:
data1 = pd.read_csv('titanic_predictions3.csv')

In [125]:
ls

 Volume in drive C is Windows
 Volume Serial Number is E8A9-D000

 Directory of C:\Users\Shrijan Aryal\Titanic

04/03/2025  09:18 PM    <DIR>          .
04/03/2025  09:18 PM    <DIR>          ..
03/30/2025  12:04 AM    <DIR>          .ipynb_checkpoints
03/29/2025  04:51 PM            33,673 best_model.pkl
04/03/2025  08:14 PM            42,939 best_model2.pkl
04/03/2025  09:05 PM            42,663 best_model3.pkl
04/03/2025  08:51 PM             3,258 submissionApril.csv
04/03/2025  08:52 PM             1,008 submissionApril.zip
03/30/2025  09:40 PM             3,258 submissionI.csv
03/30/2025  09:41 PM             1,000 submissionI.zip
03/24/2025  02:23 PM            28,629 test.csv
04/03/2025  09:06 PM           829,869 Titanic.ipynb
04/03/2025  09:18 PM           113,911 Titanic_prediction.ipynb
03/30/2025  12:03 AM            31,102 titanic_predictions.csv
04/03/2025  08:50 PM            31,948 titanic_predictions2.csv
04/03/2025  09:18 PM            31,948 titanic_predictions3.csv
03/26/2025  06:49 PM            61,194 Titanic_train.csv
              14 File(s)      1,256,400 bytes
               3 Dir(s)  309,179,482,112 bytes free

In [133]:
data1.head()

,PassengerId,Name,Pclass,Sex_male,Age,Family,Fare,Embarked,Deck,Pclass_Sex,IsElderly,Ticket,Survived
0,892,"Kelly, Mr. James",3,1,34.5,1,7.8292,2,5.0,3,0,330911,0
1,893,"Wilkes, Mrs. James (Ellen Needs)",3,0,47.0,2,7.0000,1,5.0,0,0,363272,1
2,894,"Myles, Mr. Thomas Francis",2,1,62.0,1,9.6875,2,5.0,2,1,240276,0
3,895,"Wirz, Mr. Albert",3,1,27.0,1,8.6625,1,5.0,3,0,315154,0
4,896,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",3,0,22.0,3,12.2875,1,5.0,0,0,3101298,1

In [153]:
final_data = data1[['PassengerId','Survived']]

In [154]:
final_data.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [155]:
final_data.to_csv('submission.csv', index=False)

In [156]:
ls

 Volume in drive C is Windows
 Volume Serial Number is E8A9-D000

 Directory of C:\Users\Shrijan Aryal\Titanic

04/03/2025  09:31 PM    <DIR>          .
04/03/2025  09:31 PM    <DIR>          ..
03/30/2025  12:04 AM    <DIR>          .ipynb_checkpoints
03/29/2025  04:51 PM            33,673 best_model.pkl
04/03/2025  08:14 PM            42,939 best_model2.pkl
04/03/2025  09:05 PM            42,663 best_model3.pkl
04/03/2025  09:24 PM            35,855 best_model4.pkl
04/03/2025  08:51 PM             3,258 submissionApril.csv
04/03/2025  08:52 PM             1,008 submissionApril.zip
04/03/2025  09:18 PM             3,258 submissionApril2.csv
04/03/2025  09:19 PM             1,010 submissionApril2.zip
04/03/2025  09:31 PM             3,258 submissionApril3.csv
03/30/2025  09:40 PM             3,258 submissionI.csv
03/30/2025  09:41 PM             1,000 submissionI.zip
03/24/2025  02:23 PM            28,629 test.csv
04/03/2025  09:25 PM           829,187 Titanic.ipynb
04/03/2025  09:30 PM            98,646 Titanic_prediction.ipynb
03/30/2025  12:03 AM            31,102 titanic_predictions.csv
04/03/2025  08:50 PM            31,948 titanic_predictions2.csv
04/03/2025  09:18 PM            31,948 titanic_predictions3.csv
04/03/2025  09:30 PM            30,227 titanic_predictions4.csv
03/26/2025  06:49 PM            61,194 Titanic_train.csv
              19 File(s)      1,314,061 bytes
               3 Dir(s)  309,293,203,456 bytes free